### ISSUE TITLE
Start having general layout made out with Main Storyboard

### ISSUE THREAD

**Issue by Brandon-Urbina** [Lunch-Party/LunchParty#1]
**Reference** 
- [Configure Navigation Controller](https://guides.codepath.org/ios/Navigation-Controller)
- [Configure Tab Controller](https://guides.codepath.org/ios/Tab-Bar-Controller-Guide)
- [Configure Container View Controller](https://guides.codepath.org/ios/Container-View-Controllers)

**Tasks**
- [x] Set up project and repository
- [x] Get general layout setup
- [x] Main Storyboard is generally made up
