### ISSUE TITLE
Restaurant GPS and voting features implemented

### ISSUE THREAD

**Issue by Brandon-Urbina** [Lunch-Party/LunchParty#3]
**Reference**

- [Retrieveing Location](https://guides.codepath.org/ios/Location-Quickstart)
- [Maps](https://guides.codepath.org/ios/Maps)

**Tasks**

- [ ] Retrieve users location

- [ ] Maps integrated using Google Maps API

- [ ] Voting system finished and ready
