### ISSUE TITLE
Account Creation and Login Setup

### ISSUE THREAD

**Issue by Brandon-Urbina** [Lunch-Party/LunchParty#4]
**Reference**
[Instagram Clone Login Youtube Playlist](https://www.youtube.com/playlist?list=PLrT2tZ9JRrf74emXdHwSG6Q46-DEvuNA6)

**Tasks**

- [ ] Server is set up and maintained

- [x] Login/ Setup account

- [x] Navigation is set up

- [x] Voting features are implemented
